### ISSUE TITLE
Create a Git Pre Commit Hook to run ESLint

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/nodecloud-legacy#19]
Let's create a Git Pre Commit Hook to run ESLint in our NodeCloud repos to avoid ourselves pushing codes with lint errors. 

Follow these steps:

1. Create a file in `.git/hooks` as `pre-commit`
2. Add these contents https://gist.github.com/agentmilindu/b61f4f8e23742d7cc394290d8a8c2378
3. `chmod +x .git/hooks/pre-commit`

![image](https://user-images.githubusercontent.com/1391468/34318287-4822b722-e7ea-11e7-8622-6ba9e99ab71f.png)
_Image Source: http://www.sterlinghamilton.com/git-hook-pre-commit-for-debug-comments/_

**Comment by agentmilindu** [comment]
**Commits with no lint errors**

![image](https://user-images.githubusercontent.com/1391468/34318358-b2a9ee20-e7eb-11e7-8ea2-01a855c61d95.png)

**Commits with lint errors**

![image](https://user-images.githubusercontent.com/1391468/34318362-c725921e-e7eb-11e7-9cac-f608ef4193ad.png)

**Comment by padamchopra** [comment]
![eslinting-nodecloud](https://user-images.githubusercontent.com/19776024/34325847-02cd43f6-e8c4-11e7-8d7a-5dde24382848.png)
**For others: To know more about creating git hooks, refer this-**
https://scotch.io/tutorials/using-git-hooks-in-your-development-workflow
