### ISSUE TITLE
mocha test/storage/aws-s3.js  testing actually creates a bucket in s3

### ISSUE THREAD

**Issue by dilantha111** [leopardslab/nodecloud-legacy#54]
# This is a Bug Report

## Description

* Unit testing storage with provider as aws, actually creates a bucket in the aws
* In the Unit test intercepting the http request to create a bucket and mock the http response

## Additional Data

* ***Operating System***: Linux mint 18.3 Cinnamon 64-bit
* ***Stack Trace***:
AWS S3
    1) should create S3 bucket
(node:10378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
(node:10378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ should not delete S3 bucket (1296ms)
    ✓ should create multipart upload (1055ms)
    ✓ should list all buckets (1337ms)
(node:10378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: expected 'https://ncbucketcr.s3.us-west-2.amazonaws.com/key' to equal 'https://ncbucketcr.s3-us-west-2.amazonaws.com/key'
    2) should upload an arbitary sized buffer, blob, or stream

  3 passing (8s)
  2 failing

  1) AWS S3
       should create S3 bucket:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) AWS S3
       should upload an arbitary sized buffer, blob, or stream:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by raju249** [comment]
Would you like to take up this issue @dilantha111 ?

**Comment by dilantha111** [comment]
Yes I would like to work on that @raju249 . Thanks. So shall I proceed ?

**Comment by raju249** [comment]
Since this is a bug in tests, I think you can proceed to fix it 😄 
/cc @rehrumesh @rajikaimal
